spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
  config:
    import:
        - optional:file:src/main/resources/.env[.properties]

prompt:
  fashion:
    system-message: ${FASHION_SYSTEM_MESSAGE:}
    user-message: ${FASHION_USER_MESSAGE:}


slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL:}